### ISSUE TITLE
Learning AWS, Lambda, SES and Updating the AWS SDK Mock Module

### ISSUE THREAD

**Issue by nelsonic** [dwyl/apprenticeship#10]
Most people beginning an apprenticeship haven't had any exposure to **A**mazon **W**eb **S**ervices (**AWS**). This is to be _expected_ given that there is [_so_ much to learn](https://github.com/dwyl/the-book/issues/69) _already_! 

AWS is _by far_ the most popular "Cloud" ("infrastructure-as-a-serivce") provider, so learning how to use it will be beneficial to _any_ apprentice regardless of where you end up working!

@dwyl we have a _number_ of repositories related to AWS: https://github.com/dwyl?q=aws including _several_ tutorials e.g:
![image](https://user-images.githubusercontent.com/194400/28011874-ca05a45a-655b-11e7-9dac-14d2671ce81f.png)

All of these AWS-related repos need some TLC (review/updating/streamlining) to bring them up-to-date with the latest UI/SDK.

## Todo/Tasks

+  [x] Go through the `learn-aws-...` guides with your own AWS account to check the tutorials are still accurate/relevant. specifically:
  + [x] https://github.com/dwyl/learn-amazon-web-services
  + [ ] https://github.com/dwyl/learn-aws-lambda
Note: We had planned to migrate these tutorials to the "GitBook" format so that they could be published as PDF/Mobi and put on the Kindle Store (_as Free e-books!_) if you are up for this challenge, please leave a comment below!

Once you are (_reasonably_) confident in your AWS knowledge/skills our `aws-sdk-mock` module needs some TLC ...

+ [ ] Update (_re-write_) the Docs for https://github.com/dwyl/aws-sdk-mock 
+ [ ] Update [dependencies](https://david-dm.org/dwyl/aws-sdk-mock) (this is a perfect opportunity to learn `sinon` ...) 

![image](https://user-images.githubusercontent.com/194400/28012214-02267020-655d-11e7-9056-6100d76633ce.png)

The module is quite popular:
![aws-sdk-mock ](https://user-images.githubusercontent.com/194400/28011929-fe4c45b6-655b-11e7-83a4-398ef4ea6271.png)
And if who ever gives it some attention will be made a co-maintainer on NPM:
![image](https://user-images.githubusercontent.com/194400/28012380-80f79ff0-655d-11e7-98f4-72e5b92ef8fe.png)

+ [ ] There are currently [***36 issues***](https://github.com/dwyl/aws-sdk-mock/issues) and 3 PRs open ... we should aim to get this down to _zero_ if possible.

**Comment by finnhodgkin** [comment]
Sounds great! Me and @ZooeyMiller are happy to have a go :+1:

**Comment by ZooeyMiller** [comment]
Really happy to work on this! Will get cracking :tada:

**Comment by ZooeyMiller** [comment]
`today` we ran through `learn-amazon-web-services` and raised issues on the repo as we went, we've made prs relating to them, one is a [WiP]. It took us a little longer than hoped due to getting stuck on a couple of things but these have been tracked in issues and solutions will be added to the readme.

**Comment by nelsonic** [comment]
@finnhodgkin & @ZooeyMiller please remember to create any ("sub") issues for tasks and _estimate_ (_i.e. "time box"_) how much time you intend to spend working on the issue. thanks!

**Comment by nelsonic** [comment]
Closing as the `aws-sdk-mock` was comprehensively updated: https://github.com/dwyl/aws-sdk-mock/pull/277 ✅
