### ISSUE TITLE
How to Accelerate Learning English

### ISSUE THREAD

**Issue by nelsonic** [dwyl/apprenticeship#34]
Love it or hate it, the language of _international_ **creative technology** is **English**. 🇬🇧 
Design, UX and coding skills are great, but if creative skills are not paired with superior communication skills you will not reach your potential. The better you know how to communicate in English, the faster you will make progress toward your goals.

## Reading

By far the most effective _long term_ strategy for learning English is [_reading_](https://github.com/nelsonic/nelsonic.github.io/issues/665) books on a topic that interest you. Published books (_from respected publishers_) have several advantages over online material. 
The top 3 advantages of reading books are:
1. **Authors** have devoted significant time to researching, organising and writing the book so the knowledge is condensed and can be consumed in an efficient way. It will only take you a few hours to read a book that may have taken _years_ of research. 
2. **Editors** have fact-checked and made corrections to the content so readers don't have to.
3. ***Finite*** (_in length/scope_), can be read in a logical sequence and a predictable amount of time. Simply break down the number of pages by the time you want to read it in.

Reading books can take quite a lot of time. As a _dyslexic_ + _slow_ reader, it took me a _very_ long time to get through my first few books; multiple weeks per book. But the _only_ way to get better/faster at reading is to read _more_. Develop a habit of _regular_ reading early each morning. Reading is the [_best_ investment](https://github.com/nelsonic/nelsonic.github.io/issues/521#issuecomment-439862663).

## Writing

The next best way to practice English, which is complimentary to reading, is _writing_. 
Write whatever comes to mind, the more you _think_ in English the better you will get at _communicating_ your thoughts in English. If you are still thinking in a _different_ language and _translating_ your thoughts into English, you need to write!

## Grammar, Phrasing and Spelling

Writing as much as you can will not _automatically_ make you a better writer unless you actively seek _feedback_. Feedback can come from a human or it can can come from AI such as a grammar/spelling checker. 

## Todo 

+ [ ] Install a _second_ (_or **third**_) version of Google Chrome
  (e.g: https://www.google.com/chrome/canary or [https://www.chromium.org/getting-involved](https://www.chromium.org/getting-involved/download-chromium) ⬇️)
 
+ [ ] Add Grammarly to the _alternative_ Chrome version https://www.grammarly.com
![image](https://user-images.githubusercontent.com/194400/76809838-04dcb900-67e4-11ea-92cd-007053aeb1ed.png)

> Note: we do **not** recommend installing chrome plugins in your **`main`** chrome browser because we do **not _trust_** plugins that have access to **all** our data. But in a secondary browser that you _only_ use for writing, it's fine. Just don't use it for your Online Banking or other sensitive data!

+ [ ] Write as much as you can in _English_ in the Grammarly-enabled Chrome browser.
